openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger хранилище питомцев
  license:
    name: MIT
servers:
  - url: http://127.0.0.1:8000/
  - url: http://api.myserver.ru/v1
paths:
  /pets:
    get:
      summary: список всех питомцев
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: Как много можно вернуть элементов (max 100)
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        '200':
          description: Постраничный возврат элементов
          headers:
            x-next:
              description: Ссылка на следующую страницу 
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: Неожиданная ошибка 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Создание питомца
      operationId: createPets
      tags:
        - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '201':
          description: Пустой ответ
        default:
          description: Неожиданная ошибка 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: Информация о питомце
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: id питомца
          schema:
            type: string
      responses:
        '200':
          description: Ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: Неожиданная ошибка 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
                
                
                
                
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string